name: e_commerce_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_slidable: ^2.0.0
  google_fonts: ^3.0.1
  intl: ^0.17.0
  mockito: ^5.3.0
  mocktail_image_network: ^0.3.1
  provider: ^6.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/data/
    - assets/data/cart_data.json
  uses-material-design: true
